name: Build-and-deploy
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install dp
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                path: dist
                name: builded-files
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get-builded-project
              uses: actions/download-artifact@v3
              with:
                name: builded-files