name: Deploy Angular App
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Get repository code
            uses: actions/checkout@v3
          - name: Install depedencies
            run: npm ci
          - name: Test application
            run: npm test -- --watch=false --browsers=ChromeHeadless
          - name: Build application
            run: npm run build
          - name: Deploy
            run: echo Deploying   