name: Deploy Angular App
on:
  push:
    branches:
      - 'master'
    # paths-ignore:
    #   - './github/workflows/*'
jobs:
    test_my_app:
        runs-on: ubuntu-latest
        steps:
          - name: Get repository code
            uses: actions/checkout@v3
          - name: Cache deps
            uses: actions/cache@v3
            with:
              path: ~/.npm
              key: node-modules-${{ hashFiles('**/package-lock.json') }}
          - name: Install depedencies
            run: npm ci
          - name: Test application
            run: npm test -- --watch=false --browsers=ChromeHeadless
    # lint:
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Get repository code
    #       uses: actions/checkout@v3
    #     - name: Install dependencies
    #       run: npm ci
    #     - name: Lint application
    #       run : npm run lint
    build:
      runs-on: ${{ matrix.os }}
      needs: test_my_app
      strategy:
        matrix:
          my-node-version: [14, 16]
          os: [ubuntu-latest, windows-latest]
      steps:
        - name: Get repository code
          uses: actions/checkout@v3
        - name: Install Node Js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.my-node-version}}
        - name: Cache deps
          uses: actions/cache@v3
          with:
              path: ~/.npm
              key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          run: npm ci
        - name: Build application
          run: npm run build
        - name: Deploy
          run: echo Deploying

        