name: Test Angular App
on: push
jobs:
    test_my_app:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install depedencies
              run: npm ci
            - name: Test application
              run: npm test -- --watch=false --browsers=ChromeHeadless 